---
sudo: required

services:
    - docker

before_install:
    - docker build --build-arg TIKA_VER=$TIKA_VER --build-arg APACHE_STORM_VER=$APACHE_STORM_VER -t $DOCKER_USERNAME/spamscope-deps .;

# command to run tests
script:
    - docker run --rm $DOCKER_USERNAME/spamscope-deps thug -V;
    - docker run --rm $DOCKER_USERNAME/spamscope-deps storm version;

after_success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    - docker push $DOCKER_USERNAME/spamscope-deps;

notifications:
    email: false
    slack:
        secure: "V3isMWabw1J5eWwToNLrU9AI5TdB7AMM4FpatM0aZfvUvuWKWKfOlHd8C0cc4IjjbHNpnSy+AHd3i3/zjRaefhnYeOW1WwEKgGQM5gnoaJHBrXTA408l0iZpCL9Wa+zBImxzM0mJaBs9517d2hLqmcgt4kEu7WJwskR8HkLR2Q/F0GqfBewQ7uvbFT7/WZWEELrKKQgc9NBbbo41vvzkVw4KKcsuQsSvTMWpTEAcPCw2V5s+vn9F5RQzjwV06yncvoxr/W0kPAjw1Q1nQS6UDeI83rWMRjgxcY3kSnOEuGMZ/Fyx5gZ8xIHMUqYfgEIv9PhkxTIZREWO0FulX9A+evpFuRkmtMZ8KdUJ1USrjsvlQ56qMWMcMZqIk6dv5EgJ0fV68bCpaLe7IiLnvQIQQ8UY0JPC32ltpLjynsxzco3ARWuNYcYdiBaoDjwYu1T5WDSk/tHc/+3oxggqbvI02gIZcaX2aKa7dguTSPuyUNOuEc/SvY4X5QZ/EnMD2h9g58wN4sFqhmfxhsoj0YS/7wdfzvRQrFi5OM/xkBiYgkC6Rok4xrqPh0JWiorGTiyaX2IKmLv2G/uYVY0X4UPP029YaDK9yLDRsXcBEVFY5xSBRsiWM6keHDtyB4rVl1VPmTjV1YbaJOK2RrwC9uV3YMKUYQJQEHnzme6xHG7ITFQ="
